name: Publish release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup build file
        id: set_build_name
        shell: bash
        run: |
          repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          if [ "${{ runner.os }}" = "Windows" ]; then
            ext=".exe"
          elif [ "${{ runner.os }}" = "Linux" ]; then
            ext=".bin"
          elif [ "${{ runner.os }}" = "macOS" ]; then
            ext=".app"
          else
            ext=""
          fi
          build_file="${repo_name}_${{ runner.os }}_${{ runner.arch }}_build${ext}"
          echo "build_file=${build_file}" >> "$GITHUB_OUTPUT"

      - name: Build application
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          output-file: ${{ steps.set_build_name.outputs.build_file }}
          disable-console: true
          enable-plugins: pyside6

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app
          include-hidden-files: true

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
